title: Ankur Jain
email: email@ankurjain.pro
description: >- 
  Senior Mobile Consultant | iOS & Flutter Expert

baseurl: ""
url: "https://iamankurjain.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

future: true

minima:
  social_links:
    github: iamankurjain
    linkedin: ankurjain-dev
    email: email@ankurjain.pro

  navigation:
    - title: Home
      url: /
    - title: Blog
      url: /blog/
    - title: About
      url: /about/